### PR TITLE
Homepage

### PR DESCRIPTION
**Pull request by satoshimikoto**
beta version of adding photo implemented

### CODE REVIEW

**Review by ThibaultPaulmann — CHANGES_REQUESTED** [review]
Needs work on submitting the picture

**Review by philippglasmacher — APPROVED** [review]

**Comment by satoshimikoto** [comment]
newedit

**Comment by philippglasmacher** [comment]
> Needs work on submitting the picture

done

**Review by ThibaultPaulmann — APPROVED** [review]

**Comment by ThibaultPaulmann** [comment]
remember Philipp and I need to setup our local environment with Mike's cloudinary key

**Pull request merged**
